version: 2
project_name: catsync

release:
  prerelease: true

builds:
  - id: CatSync
    main: ./cmd
    binary: CatSync
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - arm
      - amd64
      - arm64
      - "386"
    goarm:
      - "6"
      - "7"
    goamd64:
      - v1
      - v2
      - v3
      - v4
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags=-static,-Wl,-O3
      - "-X github.com/Sn0wo2/CatSync/version.version={{.Version}}"
      - "-X github.com/Sn0wo2/CatSync/version.commit={{.Commit}}"
      - "-X github.com/Sn0wo2/CatSync/version.date={{.Date}}"

dockers:
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v1"
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v1
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v2"
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v2
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v3"
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v3
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v4"
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v4
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-armv6"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
  - image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-386"
    use: buildx
    goos: linux
    goarch: "386"

docker_manifests:
  - name_template: "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v1"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v2"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v3"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v4"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-armv6"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-386"

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: "^.*feat(?:\\([^)]+\\))?:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix(?:\\([^)]+\\))?:+.*$"
      order: 1
    - title: "⚡️ Performance Improvements"
      regexp: "^.*perf(?:\\([^)]+\\))?:+.*$"
      order: 2
    - title: "📝 Documentation"
      regexp: "^.*docs(?:\\([^)]+\\))?:+.*$"
      order: 3
    - title: "🔧 Maintenance & Chores"
      regexp: "^.*chore(?:\\([^)]+\\))?:+.*$"
      order: 4
    - title: "♻️ Code Refactoring"
      regexp: "^.*refactor(?:\\([^)]+\\))?:+.*$"
      order: 5
    - title: "🧪 Tests"
      regexp: "^.*test(?:\\([^)]+\\))?:+.*$"
      order: 6
    - title: "📦 Dependency Updates"
      regexp: "^.*deps(?:\\([^)]+\\))?:+.*$"
      order: 7
    - title: "📍 Others"
      order: 999