version: 2
project_name: catsync

release:
  prerelease: auto

builds:
  - id: CatSync
    main: ./cmd
    binary: CatSync
    env:
      - CGO_ENABLED=0
      - TZ=Asia/Shanghai
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      - v3
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags=-static,-Wl,-O3
      - -X github.com/Sn0wo2/CatSync/version.version={{.Version}}
      - -X github.com/Sn0wo2/CatSync/version.commit={{.Commit}}
      - -X github.com/Sn0wo2/CatSync/version.date={{.Date}}
      - -X github.com/Sn0wo2/CatSync/version.os={{.Os}}
      - -X github.com/Sn0wo2/CatSync/version.arch={{.Arch}}{{.Amd64}}{{.Arm}}

dockers:
  - image_templates:
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v1
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v1
    build_flag_templates:
      - --label=org.opencontainers.image.description=Sync the「cat」config.
      - --label=org.opencontainers.image.source=https://github.com/Sn0wo2/CatSync
      - --label=org.opencontainers.image.url=https://github.com/Sn0wo2/CatSync
      - --label=org.opencontainers.image.vendor=Sn0wo2
      - --label=org.opencontainers.image.authors=Sn0wo2
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.license.name=MIT License
      - --label=org.opencontainers.image.license.spdx=MIT
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.revision={{.Commit}}
      - --label=org.opencontainers.image.git.branch={{ .Branch }}
      - --label=org.opencontainers.image.created={{.Date}}
      - --platform=linux/amd64/v1
  - image_templates:
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v3
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v3
    build_flag_templates:
      - --label=org.opencontainers.image.description=Sync the「cat」config.
      - --label=org.opencontainers.image.source=https://github.com/Sn0wo2/CatSync
      - --label=org.opencontainers.image.url=https://github.com/Sn0wo2/CatSync
      - --label=org.opencontainers.image.vendor=Sn0wo2
      - --label=org.opencontainers.image.authors=Sn0wo2
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.license.name=MIT License
      - --label=org.opencontainers.image.license.spdx=MIT
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.revision={{.Commit}}
      - --label=org.opencontainers.image.git.branch={{ .Branch }}
      - --label=org.opencontainers.image.created={{.Date}}
      - --platform=linux/amd64/v3
  - image_templates:
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-arm64
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --label=org.opencontainers.image.description=Sync the「cat」config.
      - --label=org.opencontainers.image.source=https://github.com/Sn0wo2/CatSync
      - --label=org.opencontainers.image.url=https://github.com/Sn0wo2/CatSync
      - --label=org.opencontainers.image.vendor=Sn0wo2
      - --label=org.opencontainers.image.authors=Sn0wo2
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.license.name=MIT License
      - --label=org.opencontainers.image.license.spdx=MIT
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.revision={{.Commit}}
      - --label=org.opencontainers.image.git.branch={{ .Branch }}
      - --label=org.opencontainers.image.created={{.Date}}
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v1
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v3
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-arm64
  - name_template: ghcr.io/sn0wo2/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v1
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-amd64v3
      - ghcr.io/sn0wo2/{{ .ProjectName }}:{{ .Tag }}-arm64

changelog:
  use: github
  groups:
    - title: 🚀 Features
      regexp: "^.*feat(?:\\([^)]+\\))?:+.*$"
      order: 0
    - title: 🐛 Bug Fixes
      regexp: "^.*fix(?:\\([^)]+\\))?:+.*$"
      order: 1
    - title: ⚡️ Performance Improvements
      regexp: "^.*perf(?:\\([^)]+\\))?:+.*$"
      order: 2
    - title: 📝 Documentation
      regexp: "^.*docs(?:\\([^)]+\\))?:+.*$"
      order: 3
    - title: 🔧 Maintenance & Chores
      regexp: "^.*chore(?:\\([^)]+\\))?:+.*$"
      order: 4
    - title: ♻️ Code Refactoring
      regexp: "^.*refactor(?:\\([^)]+\\))?:+.*$"
      order: 5
    - title: 🧪 Tests
      regexp: "^.*test(?:\\([^)]+\\))?:+.*$"
      order: 6
    - title: 📦 Dependency Updates
      regexp: "^.*deps(?:\\([^)]+\\))?:+.*$"
      order: 7
    - title: 📍 Others
      order: 999
