version: 2
project_name: catsync

release:
  prerelease: auto

builds:
  - id: CatSync
    main: ./cmd
    binary: CatSync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "5"
      - "6"
      - "7"
    goamd64:
      - v1
      - v2
      - v3
      - v4
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags=-static,-Wl,-O3
      - "-X github.com/Sn0wo2/CatSync/version.version={{.Version}}"
      - "-X github.com/Sn0wo2/CatSync/version.commit={{.Commit}}"
      - "-X github.com/Sn0wo2/CatSync/version.date={{.Date}}"

dockers_v2:
  - images:
      - "ghcr.io/sn0wo2/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Sync the「cat」config."
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
    platforms:
      - linux/amd64/v1
      - linux/amd64/v2
      - linux/amd64/v3
      - linux/amd64/v4
      - linux/arm/5
      - linux/arm/6
      - linux/arm/7
      - linux/arm64
      - linux/386
      - linux/mips
      - linux/mipsle
      - linux/mips64
      - linux/mips64le
      - linux/ppc64le
      - linux/riscv64
      - linux/s390x
    ids:
      - CatSync

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: "^.*feat(?:\\([^)]+\\))?:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix(?:\\([^)]+\\))?:+.*$"
      order: 1
    - title: "⚡️ Performance Improvements"
      regexp: "^.*perf(?:\\([^)]+\\))?:+.*$"
      order: 2
    - title: "📝 Documentation"
      regexp: "^.*docs(?:\\([^)]+\\))?:+.*$"
      order: 3
    - title: "🔧 Maintenance & Chores"
      regexp: "^.*chore(?:\\([^)]+\\))?:+.*$"
      order: 4
    - title: "♻️ Code Refactoring"
      regexp: "^.*refactor(?:\\([^)]+\\))?:+.*$"
      order: 5
    - title: "🧪 Tests"
      regexp: "^.*test(?:\\([^)]+\\))?:+.*$"
      order: 6
    - title: "📦 Dependency Updates"
      regexp: "^.*deps(?:\\([^)]+\\))?:+.*$"
      order: 7
    - title: "📍 Others"
      order: 999
