services:
  CatSync:
    image: ghcr.io/sn0wo2/catsync:latest
    container_name: CatSync
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
