// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Sn0wo2/CatSync/framework"
	"github.com/Sn0wo2/CatSync/runtime"
	"github.com/Sn0wo2/caelum"
)

// Injectors from wire.go:

func InitializeCatSync() (*catSync, error) {
	loadResult, err := NewConfig()
	if err != nil {
		return nil, err
	}
	logger := NewLogger(loadResult)
	manager, err := NewRuntime(loadResult, logger)
	if err != nil {
		return nil, err
	}
	ctx := NewParams(manager, logger)
	fb := NewFramework(ctx, manager)
	mainCatSync := &catSync{
		Logger:  logger,
		Runtime: manager,
		Server:  fb,
	}
	return mainCatSync, nil
}

// wire.go:

type catSync struct {
	Logger  *caelum.Logger
	Runtime *runtime.Manager
	Server  *framework.FB
}
