// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Sn0wo2/CatSync/config"
	"github.com/Sn0wo2/CatSync/framework"
	"github.com/Sn0wo2/CatSync/params"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeApp() (*appContext, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	logger := NewLogger(config)
	ctx := NewParams(config, logger)
	framework := NewFramework(ctx)
	mainAppContext := &appContext{
		Cfg:    config,
		Logger: logger,
		Params: ctx,
		App:    framework,
	}
	return mainAppContext, nil
}

// wire.go:

type appContext struct {
	Cfg    *config.Config
	Logger *zap.Logger
	Params *params.Ctx
	App    *framework.Framework
}
